name: Release

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ Test, Dependabot ]
    types: 
      - completed

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Build
        id: build
        run: |
          go build -ldflags "-s -w" -o flows
          go build -ldflags "-s -w" -o run ./commit
          echo "date=$(TZ=PRC date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Delete Old Release
        uses: actions/github-script@v7
        with:
          script: |
            let release
            try {
              release = await github.rest.repos.getReleaseByTag({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag: 'v1.0'
              })
            } catch(e) {
              console.error(e)
              return
            }

            await github.rest.repos.deleteRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: release.data.id
            })

            await github.rest.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'tags/v1.0'
            })

      - name: Pack
        run: tar cvzf release.tar.gz flows config.ini.default

      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0
          name: ${{ steps.build.outputs.date }}
          body: ${{ steps.build.outputs.date }}
          files: |
            release*
            run
